name: YouTube Discord Bot

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check-youtube:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script
        env:
          WEBHOOK_DREAM_REALM: ${{ secrets.WEBHOOK_DREAM_REALM }}
          WEBHOOK_TEST_1: ${{ secrets.WEBHOOK_TEST_1 }}
          WEBHOOK_TEST_2: ${{ secrets.WEBHOOK_TEST_2 }}
        run: python script.py

      - name: Sauvegarder l'historique
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Mise à jour automatique" || exit 0
          git push
